/* ステージ仕様（教育的な中身は手書き、迷路はここから生成） */
module.exports = [
{
  id: '1-1', chapter: '第1章 力学の単位', title: 'よけいなものを捨てる',
  story: "同じものどうしで割ると、単位は消えて「何倍か」だけが残る。持っている m を捨てて EXIT へ。",
  start: 'm', goal: '1', ops: ['/m'], gates: 0,
  C: 4, R: 3, braid: 0.30, decoys: 2, seed: 11, short: true, wantJunctions: 8, seedTries: 240,
  decoyPool: ['*m', '*s', '*kg'],
  tip: "「長さ ÷ 長さ」は、何倍かを表すただの数。倍率に単位はいらない。だから m を m で割ると消える。",
  meaning: "同じ種類の量どうしの比には、単位がない",
  formula: 'm ÷ m = 1',
  quiz: { q: '「無次元」の量はどれ？', choices: ['速さ', '摩擦係数', '加速度', '力'], ans: 1,
          exp: '摩擦係数 μ は 力÷力 なので単位が消える。無次元量は単位を持たない。' }
},
{
  id: '1-2', chapter: '第1章 力学の単位', title: '速さをつくる',
  story: "速さとは「決まった時間に、どれだけ進めるか」。だから距離を時間で割る。",
  start: 'm', goal: 'm/s', ops: ['/s'], gates: 0,
  C: 5, R: 4, braid: 0.30, decoys: 3, seed: 7, short: true, wantJunctions: 8, seedTries: 240,
  decoyPool: ['*s', '*kg', '/kg', '*m'],
  tip: "1秒あたり何メートル進むか、を考える。「1秒あたり」は時間で割るということ。だから ÷s。",
  meaning: "速さ＝1秒あたりに進む距離",
  formula: 'v = x / t  →  m / s',
  quiz: { q: 'm/s をもう一度「÷s」で割ると何になる？', choices: ['速さ', '加速度', '力', '距離'], ans: 1,
          exp: 'm/s ÷ s = m/s²。これは加速度の単位。' }
},
{
  id: '1-3', chapter: '第1章 力学の単位', title: '力をつくる',
  story: "力とは「物の速さを、どれだけ勢いよく変えられるか」。重い物ほど、変えるのに大きな力がいる。",
  start: 'kg', goal: 'N', ops: ['*m', '/s', '/s'], gates: 0,
  C: 6, R: 5, braid: 0.28, decoys: 5, seed: 3, short: true, wantJunctions: 14, seedTries: 240,
  decoyPool: ['*s', '*kg', '/kg', '/m', '*m'],
  tip: "力＝質量×加速度。加速度は「速さが1秒でどれだけ変わるか」なので、速さをもう一度 時間で割ったもの。 つまり質量に、距離を掛けて時間で2回割る。",
  meaning: "力＝質量 ×（速さの変わりかた）",
  formula: 'F = ma  →  N = kg · m/s²',
  quiz: { q: '1 N はどれと同じ？', choices: ['kg·m/s', 'kg·m/s²', 'kg·m²/s²', 'kg/s²'], ans: 1,
          exp: 'F = ma の右辺は kg × m/s² = kg·m/s²。' }
},
{
  id: '1-4', chapter: '第1章 力学の単位', title: '関門をひらく',
  story: "動いている物は、それだけでエネルギーを持っている。その大きさは「質量 × 速さ × 速さ」で決まる。",
  start: 'm/s', goal: 'J', ops: ['*kg', '*m', '/s'], gates: 1,
  C: 6, R: 5, braid: 0.26, decoys: 6, seed: 5, wantJunctions: 14, seedTries: 240,
  decoyPool: ['*s', '/kg', '/m', '*m'],
  tip: "運動エネルギーは 質量 × 速さの2乗。いま持っているのは速さ1つぶんなので、 質量を掛け、さらに速さをもう1つぶん（距離を掛けて時間で割る）掛ける。",
  meaning: "エネルギー＝質量 × 速さ²",
  formula: 'W = Fx  →  J = N·m = kg·m²/s²',
  quiz: { q: '1 J はどれと同じ？', choices: ['N·m', 'N/m', 'N·s', 'N/s'], ans: 0,
          exp: '仕事 = 力 × 距離 なので J = N·m。' }
},
{
  id: '2-1', chapter: '第2章 相殺と関門', title: '相殺のコツ',
  story: "仕事率とは「1秒あたり、どれだけのエネルギーを使うか」。同じ仕事でも、速く終わらせるほど仕事率は大きい。",
  start: 'J', goal: 'W', ops: ['/kg', '*kg', '/s'], gates: 1,
  C: 6, R: 6, braid: 0.26, decoys: 7, seed: 2, wantJunctions: 17, seedTries: 240,
  decoyPool: ['*s', '*m', '/m', '*kg'],
  tip: "「1秒あたり」と言われたら、時間で割る。エネルギーを時間で割ればよい。 途中の関門は、いったん質量を手放してからくぐる。",
  meaning: "仕事率＝1秒あたりに使うエネルギー",
  formula: 'P = W / t  →  W = J/s = kg·m²/s³',
  quiz: { q: '1 W はどれと同じ？', choices: ['J·s', 'J/s', 'N·s', 'N/m'], ans: 1,
          exp: '仕事率 = 仕事 ÷ 時間 なので W = J/s。' }
},
{
  id: '2-2', chapter: '第2章 相殺と関門', title: '圧力の迷宮',
  story: "圧力とは「同じ力を、どれだけ狭い面に集中させたか」。画びょうが刺さるのは、先が細いから。",
  start: 'N', goal: 'Pa', ops: ['/m', '*s', '/m', '/s'], gates: 1,
  C: 7, R: 6, braid: 0.24, decoys: 8, seed: 4, wantJunctions: 17, seedTries: 240,
  decoyPool: ['*m', '*kg', '/kg', '*s'],
  tip: "力を面積で割ると圧力になる。面積は「たて × よこ」で長さが2つぶん。だから長さで2回割る。",
  meaning: "圧力＝力 ÷ 面積",
  formula: 'p = F / S  →  Pa = N/m² = kg/(m·s²)',
  quiz: { q: '1 Pa はどれと同じ？', choices: ['N·m²', 'N/m²', 'N/m', 'N·m'], ans: 1,
          exp: '圧力 = 力 ÷ 面積 なので Pa = N/m²。' }
},
{
  id: '2-3', chapter: '第2章 相殺と関門', title: '無次元へ帰れ',
  story: "同じ種類の量どうしを割ると、単位が消えて「何倍か」だけが残る。力を力で割って、単位を持たない数に戻せ。",
  start: 'N', goal: '1', ops: ['/kg', '/m', '*s', '*s'], gates: 1,
  C: 7, R: 6, braid: 0.24, decoys: 8, seed: 9, wantJunctions: 17, seedTries: 240,
  decoyPool: ['*m', '*kg', '/s', '*s'],
  tip: "摩擦係数は「摩擦力 ÷ 垂直抗力」。力を力で割るので単位が残らない。 力を質量・長さ・時間に分解して、1つずつ消していく。",
  meaning: "力 ÷ 力＝無次元（単位を持たない数）",
  formula: '摩擦係数 μ = F / N → N/N = 1（無次元）',
  quiz: { q: '次のうち無次元でないものは？', choices: ['屈折率', 'ひずみ', 'マッハ数', '運動量'], ans: 3,
          exp: '運動量は kg·m/s。屈折率・ひずみ・マッハ数はどれも「同じ単位どうしの比」で無次元。' }
},
{
  id: '2-4', chapter: '第2章 相殺と関門', title: '長い道のり',
  story: "質量だけを持って出発。動いている物が持つエネルギーは「質量 × 速さ × 速さ」で決まる。",
  start: 'kg', goal: 'J', ops: ['*m', '*s', '/s', '*m', '/s', '/s'], gates: 2,
  C: 7, R: 6, braid: 0.24, decoys: 8, seed: 6, wantJunctions: 17, seedTries: 240,
  decoyPool: ['*kg', '/kg', '/m', '*s'],
  tip: "質量に、速さを2つぶん掛ける。速さ1つぶんは「距離を掛けて時間で割る」なので、それを2回くり返す。",
  meaning: "エネルギー＝質量 × 速さ²",
  formula: 'E = ½mv²  →  kg · (m/s)² = kg·m²/s²',
  quiz: { q: '運動エネルギー ½mv² の単位を組み立てると？', choices: ['kg·m/s', 'kg·m²/s²', 'kg·m²/s³', 'kg/(m·s²)'], ans: 1,
          exp: 'kg × (m/s)² = kg·m²/s² = J。' }
},
{
  id: '3-1', chapter: '第3章 電気・熱・累乗', title: '電気量をためる',
  story: "電流とは「1秒あたりに流れる電気の量」。ならば時間を掛ければ、流れた電気の総量になる。",
  start: 'A', goal: 'C', ops: ['*m', '*s', '/m'], gates: 1,
  C: 7, R: 6, braid: 0.26, decoys: 8, seed: 8, wantJunctions: 20, seedTries: 240,
  decoyPool: ['*kg', '/s', '/A', '*m'],
  tip: "「1秒あたりの量」に時間を掛けると総量になる。水道の勢い × 出しっぱなしにした時間 ＝ 出た水の量、と同じ。",
  meaning: "電気量＝電流 × 時間",
  formula: 'Q = It  →  C = A·s',
  quiz: { q: '1 C はどれと同じ？', choices: ['A/s', 'A·s', 'A·s²', 'A/s²'], ans: 1,
          exp: '電気量 = 電流 × 時間 なので C = A·s。' }
},
{
  id: '3-2', chapter: '第3章 電気・熱・累乗', title: '電圧をつくる',
  story: "電圧とは「電気ひとつぶんが運べるエネルギー」。同じ電気の量でも、電圧が高いほど大きな仕事ができる。",
  start: 'J', goal: 'V', ops: ['/A', '*kg', '/kg', '/s'], gates: 1,
  C: 8, R: 7, braid: 0.22, decoys: 10, seed: 12, wantJunctions: 25, seedTries: 240,
  decoyPool: ['*A', '*s', '/m', '*m'],
  tip: "「ひとつあたり」と言われたら、個数で割る。エネルギーを電気の量で割ればよい。 電気の量は「電流 × 時間」なので、電流でも時間でも割ることになる。",
  meaning: "電圧＝電気ひとつぶんが運ぶエネルギー",
  formula: 'V = W / Q  →  V = J/C = kg·m²/(s³·A)',
  quiz: { q: '1 V はどれと同じ？', choices: ['J·C', 'J/C', 'C/J', 'J/A'], ans: 1,
          exp: '電圧は「1 C あたりのエネルギー」なので V = J/C。' }
},
{
  id: '3-3', chapter: '第3章 電気・熱・累乗', title: '比熱の谷',
  story: "比熱とは「1 kg の物を1度あたためるのに、どれだけのエネルギーがいるか」。水は温まりにくく、金属は温まりやすい。",
  start: 'J', goal: 'J/kg/K', ops: ['/kg', '*m', '/m', '/K'], gates: 1,
  C: 8, R: 7, braid: 0.22, decoys: 10, seed: 13, wantJunctions: 22, seedTries: 240,
  decoyPool: ['*K', '*kg', '*s', '/s'],
  tip: "「1 kg あたり」で質量で割り、「1度あたり」で温度で割る。「〜あたり」は割り算だと覚えておけばよい。",
  meaning: "比熱＝1 kg を1度あげるのに必要なエネルギー",
  formula: 'Q = mcΔT  →  c = Q/(mΔT) = J/(kg·K)',
  quiz: { q: '比熱容量の単位はどれ？', choices: ['J·kg·K', 'J/(kg·K)', 'J/K', 'J·K/kg'], ans: 1,
          exp: 'Q = mcΔT を c について解くと c = Q/(mΔT)。単位は J/(kg·K)。' }
},
{
  id: '3-4', chapter: '第3章 電気・熱・累乗', title: '√の橋',
  story: "物は落ちるほど速くなる。落ちて得た速さは、重力の強さと落ちた距離だけで決まる。",
  start: 'm/s^2', goal: 'm/s', ops: ['*s', '*m', '/s', '^0.5'], gates: 0,
  C: 8, R: 7, braid: 0.22, decoys: 9, seed: 21, wantJunctions: 28, seedTries: 240,
  decoyPool: ['*m', '*s', '/m', '*kg'],
  tip: "加速度に距離を掛けると「速さの2乗」になる。√をとれば速さに戻る。 √の橋は、指数がすべて偶数のときしか渡れないので、渡る直前の形に気をつける。",
  meaning: "落ちて得る速さ＝√(重力の強さ × 落ちた距離)",
  formula: 'v = √(2gh)  →  √(m/s² · m) = √(m²/s²) = m/s',
  quiz: { q: '√(m²/s²) は？', choices: ['m/s', 'm²/s', 'm/s²', 'm'], ans: 0,
          exp: '平方根は指数を半分にする：m² → m、s⁻² → s⁻¹。' }
},
{
  id: '3-5', chapter: '第3章 電気・熱・累乗', title: '万有引力定数',
  story: "最終問題。万有引力の式に出てくる G は、両辺の単位をつじつま合わせするためだけに置かれた定数。その正体を単位から暴け。",
  start: 'N', goal: 'm^3/kg/s^2', ops: ['*m', '/kg', '*s', '/s', '*m', '/kg'], gates: 2,
  C: 8, R: 7, braid: 0.22, decoys: 11, seed: 15, wantJunctions: 23, seedTries: 240,
  decoyPool: ['*kg', '/m', '*s', '/s'],
  tip: "万有引力は「2つの質量を掛けて、距離の2乗で割り、G を掛けたもの」が力になる、という式。 G について解けば、力に距離を2つぶん掛けて、質量で2回割ったものになる。",
  meaning: "G は、力と質量と距離のつじつまを合わせる定数",
  formula: 'F = GMm/r²  →  G = N·m²/kg² = m³/(kg·s²)',
  quiz: { q: '万有引力定数 G の単位は？', choices: ['N·m²/kg²', 'N·kg²/m²', 'N·m/kg', 'N/(m²·kg)'], ans: 0,
          exp: 'F = GMm/r² を G について解くと G = Fr²/(Mm) → N·m²/kg²。' }
}
];
